# ~/.config/starship.toml

# Use custom format
format = '''
[┌─────>](bold green) $all
[│](bold green )$directory
[└─](bold green)$character'''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true

[character]
success_symbol = "[>](bold green) "
error_symbol = "[✗](bold red) "
